version: '3.7'
services:
  db_parcial:
    build:
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: mysql_stiven
    restart: always
    ports:
      - 5500:3306
    volumes:
      - ./Config/mysql:/var/lib/mysql
    hostname: apps_database
    networks:
      - parcial_apps
    healthcheck:
      test: ["CMD","mysql", "-u", "root", "-proot0117"]
      interval: 30s
      timeout: 10s
      retries: 5
  # --------------------------------------------------------------------
  # - The adminer is a tool for managing content in databases.
  adminer:
    image: adminer
    container_name: adminer_parcial_stiven
    restart: always
    ports:
      - 8000:8080
    networks:
      - parcial_apps
# --------------------------------------------------------------------

networks:
  parcial_apps:
    driver: bridge
    name: parcial_apps