# Usa la imagen oficial de MySQL
FROM mysql:8.0.22

# Establece variables de entorno (opcional, pero mejor en docker-compose.yml)
ENV MYSQL_ROOT_PASSWORD root0117
ENV MYSQL_DATABASE db_parcial
ENV MYSQL_USER stiven
ENV MYSQL_PASSWORD Stiven17*

# Expone el puerto de MySQL
EXPOSE 3306
